### ISSUE TITLE
npm install - not uptodate

### ISSUE THREAD

**Issue by Theng** [danke77/react-native-easy-listview-gridview#16]
I type npm install react-native-easy-listview-gridview --save

but the code is not up to date. so I got error PropType, but now I copy code from lib to replace in my node module, it work but , but it not the right way. can you make the code up to date by do npm install ?

**Comment by luco** [comment]
Install using this way:

`  "react-native-easy-listview-gridview": "git+https://github.com/danke77/react-native-easy-listview-gridview.git",`

**Comment by Theng** [comment]
Thanks you.
