### ISSUE TITLE
parse multi dimensional array

### ISSUE THREAD

**Issue by alimohammed** [danke77/react-native-easy-listview-gridview#4]
Hi,
How can I pass multi dimensional array to the render function ?
assume that I've an array with success(Array(Array('1','2','3'),Array('A','B','C'),Array('x.png','y.png','z.png'))) in the OnFetch function?

**Comment by danke77** [comment]
Could you try json array which contain json arrays?

**Comment by alimohammed** [comment]
I tried JSON array and normal array and they are parsing to the render item but I can't map them to return the view in the map loop.
look at this example:

OnFetch() {
...
success(MultiDimensionArray || JSONARRAY)
}

onRender(index,item,...) {
alert(item) <- return 3 alerts , each alert is an array while it must be 1 alert with 3 arrays each on is an array.
}
