### ISSUE TITLE
How do I re run _onFetch or reload new data

### ISSUE THREAD

**Issue by isAlmogK** [danke77/react-native-easy-listview-gridview#7]
Everything works fine when data is loaded once but when I go back and then load new data I have no way to clear the old data and re run _onFetch attached gif showing the issue 

![gridview-issue](https://user-images.githubusercontent.com/169507/28957683-ddb92012-78a7-11e7-98d5-19a47e9745e8.gif)

As you can I have to pull down to refresh the data, is there a way I can trigger that via a function call

**Comment by danke77** [comment]
@AlmogRnD 
Do you destroy the page when you go back? if you destroy the page, it re run the life cycle `componentDidMount` and the method `_onRefresh`.

**Comment by isAlmogK** [comment]
I can't really destroy it as the page its tabs which is loaded once and saved in memory this is a known issue in react navigation. 

I  have the following code 

       ```
// Subscribe to team change
        const subToTeamChange = subscribe('selectedTeam', state => {

            this.state = {
                progress: 0, // Progress bar
                indeterminate: true, // Progress bar
                photoItems:[],
                photosIsEmpty:false,
                hasPhotos:true,
                photoOffSet:0,
                photoLimit:20,

            }

            this._animate();
        }); 
```

Which subscribes to the new team section and updates the state I now need a way to force a refresh on the grid view

**Comment by chookg** [comment]
@AlmogRnD 你可以迂回做个强制刷新
`{ !this.state.refres?
                        <EasyListView
                            ref={component => this.gridview = component}
                            column={3}
                            // other props
                        />:<View></View>}`

然后更新的时候控制一下
`componentDidUpdate()
    {
        if(this.state.refresh)
        {
            this.setState({refresh: false});
        }
    }`

**Comment by isAlmogK** [comment]
@chookg this doesn't do anything, the componentDidUpdate() gets called but it does not load the new data or call the refreshHandler={this.onFetch}

**Comment by isAlmogK** [comment]
@danke77 any plans to fix/support this I can render the component but the data is cached there should be a way to clear it?
