### ISSUE TITLE
Is this component still alive and supported

### ISSUE THREAD

**Issue by isAlmogK** [danke77/react-native-easy-listview-gridview#9]
I wanted to know if this component is still and being supported I asked for a couple questions and not getting any help?

**Comment by danke77** [comment]
@AlmogRnD 
Sorry I see the issues just now and I have not any time to support the component recently. Welcome to fork this depository and reproduce it or commit pull request to make something big better.

**Comment by isAlmogK** [comment]
@danke77 that's unfortunate so I take it you're not supporting this package anymore?
